### ISSUE TITLE
Website: Link to Mailjet is broken

### ISSUE THREAD

**Issue by slashmo** [KrauseFx/MajorKey#11]
On https://majorkey.me, the link to Mailjet is missing the `https` prefix which leads to GitHub Pages routing to https://majorkey.me/mailjet.com, which cannot be found.

**Comment by KrauseFx** [comment]
Thanks, fixed with https://github.com/KrauseFx/MajorKey/commit/8fb9307a1aaba7eb3b597635a1d857f798640598
